### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by EugeneTereschenko** [EugeneTereschenko/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by anyateres** [comment]
<div class="sixteen wide column">
                            <p> Svitolina has won 15 WTA singles titles, including the 2018 WTA Finals and
                                three of five Premier 5-level tournaments in 2017: the Dubai Tennis Championships,
                                the Italian Open, and the Canadian Open. At the 2015 French Open she reached her
                                first Grand Slam quarterfinal, where she was defeated by former champion Ana
                                Ivanovic. In February 2017, after winning the title in Dubai, Svitolina became the
                                first Ukrainian woman to break into the top-10 rankings. Svitolina would finally
                                reach her first Grand Slam semifinal at the 2019 Wimbledon Championships and
                                followed it up with a second consecutive semifinal at the 2019 US Open.</p>
                        </div>

**Comment by EugeneTereschenko** [comment]
thanks
