### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by EugeneTereschenko** [EugeneTereschenko/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by anyateres** [comment]
https://www.fb.com/DonaldTrump
    realDonaldTrump@whitehouse.gov
    https://twitter.com/realDonaldTrump
    https://www.instagram.com/realDonaldTrump/
