### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by EugeneTereschenko** [EugeneTereschenko/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by anyateres** [comment]
<div class="ten wide column">
                    <h3>Experience</h3>
                    <ul class="timeline">
                        <li>
                            <p><small>2020</small></p>
                            <p>Monterrey and Strasbourg titles</p>
                        </li>
                        <li>
                            <p><small>2019</small></p>
                            <p>Two Grand Slam semifinals</p>
                        </li>
                        <li>
                            <p><small>2018</small></p>
                            <p><strong>WTA Finals champion</strong></p>
                            <ul>
                                <li>Svitolina began her 2018 season by capturing the Brisbane International title,
                                    defeating qualifier Aliaksandra Sasnovich in the final.[18] She then competed at
                                    the Australian Open as the fourth seed. She faced qualifier Ivana Jorović and
                                    won in straight sets. Against Kateřina Siniaková, Svitolina prevailed in three
                                    sets. She then had two straight-sets wins over qualifier and compatriot Marta
                                    Kostyuk and Denisa Allertová to advance to her first Australian Open
                                    quarterfinal where she was upset by Belgian Elise Mertens in straight sets.[19]
                                </li>
                            </ul>
                        </li>
                        <li>
                            <p><small>2017</small></p>
                            <p>Three Premier-5 titles and top-3 ranking</p>
                        </li>
                        <li>
                            <p><small>2016</small></p>
                            <p><strong>Olympic quarterfinal</strong></p>
                            <ul>
                                <li>Svitolina began her season at the Hopman Cup, representing Ukraine with Alexandr
                                    Dolgopolov. She was undefeated in her singles matches in the round robin stage,
                                    defeating Victoria Duval, Karolína Plíšková, and Jarmila Wolfe. Svitolina and
                                    Dolgopolov were the winners of their group, and advanced to the final, where the
                                    Australian pairing of Nick Kyrgios and Daria Gavrilova defeated them 2–0, with
                                    Svitolina losing her singles match in straight sets. At the Sydney
                                    International, Svitolina lost in the first round to Angelique Kerber. In
                                    Melbourne, she defeated Victoria Duval in straight sets, before losing to
                                    qualifier Naomi Osaka in the second round.
                                </li>
                            </ul>
                        </li>
                        <li>
                            <p><small>2015</small></p>
                            <p>First Grand Slam quarterfinal and top-20 debut</p>
                        </li>
                        <li>
                            <p><small>2014</small></p>
                            <p>Ascendancy, second WTA title</p>
                        </li>
                        <li>
                            <p><small>2013</small></p>
                            <p>First WTA title</p>
                        </li>
                    </ul>
                    <h3>Personal Life</h3>
                    <ul class="timeline">
                        <li>
                            <p><small>3 April 2021</small></p>
                            <p>Monfils proposed to Svitolina</p>
                        </li>
                        <li>
                            <p><small>2019</small></p>
                            <p>Svitolina has been in a relationship with ATP tennis player Gaël Monfils</p>
                        </li>
                    </ul>
                </div>
