### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by EugeneTereschenko** [EugeneTereschenko/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by anyateres** [comment]
<div class="six wide column">
                    <section>
                        <h3>Languages</h3>
                        <p class="tags small"><span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span></p>
                    </section>
                    <section>
                        <h3>Skills</h3>
                        <p class="tags small">Svitolina's greatest achievement as a junior was winning the French
                            Open girls event in 2010, beating Tunisian Ons Jabeur in the final.[7] She reached her
                            first professional singles final at the $25,000 tournament in Kharkiv in May 2010.</p>
                    </section>
                    <section>
                        <h3>Character</h3>
                        <p class="tags small">CALM COMPETITIVE HOSTILE</p>
                    </section>
                    <section>
                        <h3>Likes&#x1f603;</h3>
                        <p class="tags small"><a href="http://www.svitolina.com/en/news.html">Site</a></p>
                    </section>
                    <section>
                        <h3>Dislikes&#x1f61e;</h3>
                        <p class="tags small">Swearing</p>
                    </section>
                    <section>
                        <h3>Wants&#x1f97a;</h3>
                        <p class="tags small bulleted"><span class="tag">BE HEALTHY</span></p>
                    </section>
                    
                    
                </div>
